# Generated by Django 6.0.5 on 2026-05-20 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mise', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nb_collectes', models.IntegerField(default=0)),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('EN_COURS', 'EN_COURS'), ('CLOTURE', 'CLOTURE')], default='EN_COURS', max_length=20)),
                ('type_cloture', models.CharField(blank=True, choices=[('NORMALE', 'NORMALE'), ('ANTICIPEE', 'ANTICIPEE')], max_length=20, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='accounts.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectes', to='finance.cycle')),
            ],
        ),
    ]
