# Generated by Django 6.0.5 on 2026-06-17 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_add_demande_retrait'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demanderetrait',
            name='commentaire_traitement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demanderetrait',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demanderetrait',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_retrait_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demanderetrait',
            name='retrait',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_source', to='finance.retrait'),
        ),
    ]
