# Generated by Django 6.0.5 on 2026-05-20 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('COLLECTE', 'COLLECTE'), ('PENALITE', 'PENALITE'), ('PART_AGENT', 'PART_AGENT'), ('RETRAIT_CLIENT', 'RETRAIT_CLIENT')], max_length=50)),
                ('sens', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.agent')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='finance.cycle')),
            ],
        ),
    ]
