# Generated by Django 6.0.5 on 2026-05-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementfinancier',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='mouvementfinancier',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='mouvementfinancier',
            name='sens',
        ),
        migrations.AddField(
            model_name='mouvementfinancier',
            name='destination',
            field=models.CharField(
                choices=[
                    ('CLIENT', 'CLIENT'),
                    ('CYCLE', 'CYCLE'),
                    ('AGENT', 'AGENT'),
                    ('INSTITUTION', 'INSTITUTION'),
                ],
                default='CYCLE',
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mouvementfinancier',
            name='source',
            field=models.CharField(
                choices=[
                    ('CLIENT', 'CLIENT'),
                    ('CYCLE', 'CYCLE'),
                    ('AGENT', 'AGENT'),
                    ('INSTITUTION', 'INSTITUTION'),
                ],
                default='CLIENT',
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mouvementfinancier',
            name='type_mouvement',
            field=models.CharField(
                choices=[
                    ('COLLECTE', 'COLLECTE'),
                    ('MISE_RETENUE', 'MISE_RETENUE'),
                    ('PENALITE', 'PENALITE'),
                    ('RETRAIT_CLIENT', 'RETRAIT_CLIENT'),
                    ('PART_AGENT', 'PART_AGENT'),
                    ('PART_INSTITUTION', 'PART_INSTITUTION'),
                ],
                max_length=50,
            ),
        ),
    ]
