--
-- PostgreSQL database dump
--

\restrict uBh29KF6shTDHpe5dvwpbybAU74UWWbCNbZ3h5Vc1P5PgBGtSxTNArLuCmttMmB

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: finance; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA finance;


--
-- Name: calcul_commission_agent(bigint); Type: FUNCTION; Schema: finance; Owner: -
--

CREATE FUNCTION finance.calcul_commission_agent(p_agent_id bigint) RETURNS bigint
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_total bigint := 0;
BEGIN
    SELECT COALESCE(SUM(m.montant), 0)::bigint
    INTO v_total
    FROM finance.ledger_mouvementfinancier AS m
    WHERE m.agent_id = p_agent_id
      AND m.type_mouvement = 'COM_AGENT';

    RETURN v_total;
END;
$$;


--
-- Name: calcul_montant_retirable(bigint); Type: FUNCTION; Schema: finance; Owner: -
--

CREATE FUNCTION finance.calcul_montant_retirable(p_client_id bigint) RETURNS bigint
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_total bigint := 0;
BEGIN
    SELECT COALESCE(
        SUM(
            CASE
                WHEN m.type_mouvement = 'CREDIT_CLIENT' THEN m.montant
                WHEN m.type_mouvement = 'RETRAIT' THEN -m.montant
                ELSE 0
            END
        ),
        0
    )::bigint
    INTO v_total
    FROM finance.ledger_mouvementfinancier AS m
    WHERE m.client_id = p_client_id;

    RETURN v_total;
END;
$$;


--
-- Name: sync_commission_agent_from_ledger(); Type: FUNCTION; Schema: finance; Owner: -
--

CREATE FUNCTION finance.sync_commission_agent_from_ledger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_old_agent_id bigint;
    v_new_agent_id bigint;
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        v_old_agent_id := OLD.agent_id;
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        v_new_agent_id := NEW.agent_id;
    END IF;

    PERFORM finance.sync_commission_totale_for_agent(v_old_agent_id);

    IF v_new_agent_id IS DISTINCT FROM v_old_agent_id THEN
        PERFORM finance.sync_commission_totale_for_agent(v_new_agent_id);
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;


--
-- Name: sync_commission_totale_for_agent(bigint); Type: FUNCTION; Schema: finance; Owner: -
--

CREATE FUNCTION finance.sync_commission_totale_for_agent(p_agent_id bigint) RETURNS void
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF p_agent_id IS NULL THEN
        RETURN;
    END IF;

    UPDATE finance.accounts_agent
    SET commission_totale = finance.calcul_commission_agent(p_agent_id)
    WHERE id = p_agent_id;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_agent; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.accounts_agent (
    id bigint NOT NULL,
    matricule character varying(50) NOT NULL,
    telephone character varying(30) NOT NULL,
    zone character varying(100),
    commission_totale bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint,
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    CONSTRAINT accounts_agent_commission_totale_28266d36_check CHECK ((commission_totale >= 0))
);


--
-- Name: accounts_agent_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.accounts_agent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.accounts_agent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_client; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.accounts_client (
    id bigint NOT NULL,
    code_client character varying(50) NOT NULL,
    telephone character varying(30) NOT NULL,
    adresse text,
    created_at timestamp with time zone NOT NULL,
    user_id bigint,
    agent_id bigint NOT NULL,
    email character varying(254),
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL
);


--
-- Name: accounts_client_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.accounts_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.accounts_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    telephone character varying(30) NOT NULL,
    role character varying(20) NOT NULL,
    mfa_enabled boolean NOT NULL
);


--
-- Name: accounts_user_groups; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: finance_collecte; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.finance_collecte (
    id bigint NOT NULL,
    montant bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    cycle_id bigint NOT NULL,
    code character varying(50) NOT NULL,
    nb_mises integer NOT NULL,
    CONSTRAINT finance_collecte_montant_ce23f7fe_check CHECK ((montant >= 0)),
    CONSTRAINT finance_collecte_nb_mises_check CHECK ((nb_mises >= 0))
);


--
-- Name: finance_collecte_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.finance_collecte ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.finance_collecte_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finance_cycle; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.finance_cycle (
    id bigint NOT NULL,
    mise bigint NOT NULL,
    nb_collectes integer NOT NULL,
    solde_actuel bigint NOT NULL,
    statut character varying(20) NOT NULL,
    type_cloture character varying(20),
    date_cloture timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    agent_id bigint NOT NULL,
    client_id bigint NOT NULL,
    CONSTRAINT finance_cycle_mise_3d789f21_check CHECK ((mise >= 0)),
    CONSTRAINT finance_cycle_solde_actuel_ac1c8862_check CHECK ((solde_actuel >= 0))
);


--
-- Name: finance_cycle_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.finance_cycle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.finance_cycle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finance_retenue; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.finance_retenue (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    montant bigint NOT NULL,
    commission_agent bigint NOT NULL,
    commission_institution bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    cycle_id bigint NOT NULL,
    CONSTRAINT finance_retenue_commission_agent_check CHECK ((commission_agent >= 0)),
    CONSTRAINT finance_retenue_commission_institution_check CHECK ((commission_institution >= 0)),
    CONSTRAINT finance_retenue_montant_check CHECK ((montant >= 0))
);


--
-- Name: finance_retenue_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.finance_retenue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.finance_retenue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finance_retrait; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.finance_retrait (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    montant bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    CONSTRAINT finance_retrait_montant_check CHECK ((montant >= 0))
);


--
-- Name: finance_retrait_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.finance_retrait ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.finance_retrait_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ledger_mouvementfinancier; Type: TABLE; Schema: finance; Owner: -
--

CREATE TABLE finance.ledger_mouvementfinancier (
    id bigint NOT NULL,
    type_mouvement character varying(50) NOT NULL,
    montant bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    cycle_id bigint,
    destination character varying(50) NOT NULL,
    source character varying(50) NOT NULL,
    agent_id bigint,
    client_id bigint,
    CONSTRAINT ledger_mouvementfinancier_montant_81024dad_check CHECK ((montant >= 0))
);


--
-- Name: ledger_mouvementfinancier_id_seq; Type: SEQUENCE; Schema: finance; Owner: -
--

ALTER TABLE finance.ledger_mouvementfinancier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME finance.ledger_mouvementfinancier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_agent accounts_agent_matricule_key; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_agent
    ADD CONSTRAINT accounts_agent_matricule_key UNIQUE (matricule);


--
-- Name: accounts_agent accounts_agent_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_agent
    ADD CONSTRAINT accounts_agent_pkey PRIMARY KEY (id);


--
-- Name: accounts_agent accounts_agent_user_id_key; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_agent
    ADD CONSTRAINT accounts_agent_user_id_key UNIQUE (user_id);


--
-- Name: accounts_client accounts_client_code_client_key; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_client
    ADD CONSTRAINT accounts_client_code_client_key UNIQUE (code_client);


--
-- Name: accounts_client accounts_client_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_client
    ADD CONSTRAINT accounts_client_pkey PRIMARY KEY (id);


--
-- Name: accounts_client accounts_client_user_id_key; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_client
    ADD CONSTRAINT accounts_client_user_id_key UNIQUE (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_telephone_key; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_user
    ADD CONSTRAINT accounts_user_telephone_key UNIQUE (telephone);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: finance_collecte finance_collecte_code_key; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_collecte
    ADD CONSTRAINT finance_collecte_code_key UNIQUE (code);


--
-- Name: finance_collecte finance_collecte_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_collecte
    ADD CONSTRAINT finance_collecte_pkey PRIMARY KEY (id);


--
-- Name: finance_cycle finance_cycle_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_cycle
    ADD CONSTRAINT finance_cycle_pkey PRIMARY KEY (id);


--
-- Name: finance_retenue finance_retenue_code_key; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_retenue
    ADD CONSTRAINT finance_retenue_code_key UNIQUE (code);


--
-- Name: finance_retenue finance_retenue_cycle_id_key; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_retenue
    ADD CONSTRAINT finance_retenue_cycle_id_key UNIQUE (cycle_id);


--
-- Name: finance_retenue finance_retenue_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_retenue
    ADD CONSTRAINT finance_retenue_pkey PRIMARY KEY (id);


--
-- Name: finance_retrait finance_retrait_code_key; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_retrait
    ADD CONSTRAINT finance_retrait_code_key UNIQUE (code);


--
-- Name: finance_retrait finance_retrait_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_retrait
    ADD CONSTRAINT finance_retrait_pkey PRIMARY KEY (id);


--
-- Name: ledger_mouvementfinancier ledger_mouvementfinancier_pkey; Type: CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.ledger_mouvementfinancier
    ADD CONSTRAINT ledger_mouvementfinancier_pkey PRIMARY KEY (id);


--
-- Name: accounts_agent_matricule_39e80c80_like; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX accounts_agent_matricule_39e80c80_like ON finance.accounts_agent USING btree (matricule varchar_pattern_ops);


--
-- Name: accounts_client_agent_id_9ead9c55; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX accounts_client_agent_id_9ead9c55 ON finance.accounts_client USING btree (agent_id);


--
-- Name: accounts_client_code_client_c02e6921_like; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX accounts_client_code_client_c02e6921_like ON finance.accounts_client USING btree (code_client varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON finance.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON finance.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_telephone_d48be4b3_like; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX accounts_user_telephone_d48be4b3_like ON finance.accounts_user USING btree (telephone varchar_pattern_ops);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON finance.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON finance.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX accounts_user_username_6088629e_like ON finance.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON finance.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON finance.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON finance.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON finance.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON finance.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON finance.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON finance.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON finance.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: finance_collecte_code_debf0f64_like; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX finance_collecte_code_debf0f64_like ON finance.finance_collecte USING btree (code varchar_pattern_ops);


--
-- Name: finance_collecte_cycle_id_820e558e; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX finance_collecte_cycle_id_820e558e ON finance.finance_collecte USING btree (cycle_id);


--
-- Name: finance_cycle_agent_id_7e6c210e; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX finance_cycle_agent_id_7e6c210e ON finance.finance_cycle USING btree (agent_id);


--
-- Name: finance_cycle_client_id_8bf8e111; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX finance_cycle_client_id_8bf8e111 ON finance.finance_cycle USING btree (client_id);


--
-- Name: finance_retenue_code_e6b72d59_like; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX finance_retenue_code_e6b72d59_like ON finance.finance_retenue USING btree (code varchar_pattern_ops);


--
-- Name: finance_retrait_client_id_5fa709af; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX finance_retrait_client_id_5fa709af ON finance.finance_retrait USING btree (client_id);


--
-- Name: finance_retrait_code_8b57e59b_like; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX finance_retrait_code_8b57e59b_like ON finance.finance_retrait USING btree (code varchar_pattern_ops);


--
-- Name: ledger_mouvementfinancier_agent_id_4d087df0; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX ledger_mouvementfinancier_agent_id_4d087df0 ON finance.ledger_mouvementfinancier USING btree (agent_id);


--
-- Name: ledger_mouvementfinancier_client_id_d7ded9db; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX ledger_mouvementfinancier_client_id_d7ded9db ON finance.ledger_mouvementfinancier USING btree (client_id);


--
-- Name: ledger_mouvementfinancier_cycle_id_5f253673; Type: INDEX; Schema: finance; Owner: -
--

CREATE INDEX ledger_mouvementfinancier_cycle_id_5f253673 ON finance.ledger_mouvementfinancier USING btree (cycle_id);


--
-- Name: ledger_mouvementfinancier trg_sync_commission_agent_on_ledger; Type: TRIGGER; Schema: finance; Owner: -
--

CREATE TRIGGER trg_sync_commission_agent_on_ledger AFTER INSERT OR DELETE OR UPDATE ON finance.ledger_mouvementfinancier FOR EACH ROW EXECUTE FUNCTION finance.sync_commission_agent_from_ledger();


--
-- Name: accounts_agent accounts_agent_user_id_7e4836bf_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_agent
    ADD CONSTRAINT accounts_agent_user_id_7e4836bf_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES finance.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_client accounts_client_agent_id_9ead9c55_fk_accounts_agent_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_client
    ADD CONSTRAINT accounts_client_agent_id_9ead9c55_fk_accounts_agent_id FOREIGN KEY (agent_id) REFERENCES finance.accounts_agent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_client accounts_client_user_id_0e07a191_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_client
    ADD CONSTRAINT accounts_client_user_id_0e07a191_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES finance.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES finance.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES finance.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES finance.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES finance.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES finance.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES finance.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES finance.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES finance.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES finance.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_collecte finance_collecte_cycle_id_820e558e_fk_finance_cycle_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_collecte
    ADD CONSTRAINT finance_collecte_cycle_id_820e558e_fk_finance_cycle_id FOREIGN KEY (cycle_id) REFERENCES finance.finance_cycle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_cycle finance_cycle_agent_id_7e6c210e_fk_accounts_agent_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_cycle
    ADD CONSTRAINT finance_cycle_agent_id_7e6c210e_fk_accounts_agent_id FOREIGN KEY (agent_id) REFERENCES finance.accounts_agent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_cycle finance_cycle_client_id_8bf8e111_fk_accounts_client_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_cycle
    ADD CONSTRAINT finance_cycle_client_id_8bf8e111_fk_accounts_client_id FOREIGN KEY (client_id) REFERENCES finance.accounts_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_retenue finance_retenue_cycle_id_1484ef68_fk_finance_cycle_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_retenue
    ADD CONSTRAINT finance_retenue_cycle_id_1484ef68_fk_finance_cycle_id FOREIGN KEY (cycle_id) REFERENCES finance.finance_cycle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finance_retrait finance_retrait_client_id_5fa709af_fk_accounts_client_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.finance_retrait
    ADD CONSTRAINT finance_retrait_client_id_5fa709af_fk_accounts_client_id FOREIGN KEY (client_id) REFERENCES finance.accounts_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ledger_mouvementfinancier ledger_mouvementfina_agent_id_4d087df0_fk_accounts_; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.ledger_mouvementfinancier
    ADD CONSTRAINT ledger_mouvementfina_agent_id_4d087df0_fk_accounts_ FOREIGN KEY (agent_id) REFERENCES finance.accounts_agent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ledger_mouvementfinancier ledger_mouvementfina_client_id_d7ded9db_fk_accounts_; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.ledger_mouvementfinancier
    ADD CONSTRAINT ledger_mouvementfina_client_id_d7ded9db_fk_accounts_ FOREIGN KEY (client_id) REFERENCES finance.accounts_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ledger_mouvementfinancier ledger_mouvementfinancier_cycle_id_5f253673_fk_finance_cycle_id; Type: FK CONSTRAINT; Schema: finance; Owner: -
--

ALTER TABLE ONLY finance.ledger_mouvementfinancier
    ADD CONSTRAINT ledger_mouvementfinancier_cycle_id_5f253673_fk_finance_cycle_id FOREIGN KEY (cycle_id) REFERENCES finance.finance_cycle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict uBh29KF6shTDHpe5dvwpbybAU74UWWbCNbZ3h5Vc1P5PgBGtSxTNArLuCmttMmB

