from django.contrib import admin
from django.urls import path
from config.web_views import (
    AgentDetailView,
    AgentAccountToggleView,
    AgentListView,
    AgentSoftDeleteView,
    AgentUpdateView,
    ClientDetailView,
    ClientAccountToggleView,
    ClientListView,
    ClientRetraitView,
    ClientSoftDeleteView,
    ClientUpdateView,
    CommissionCycleListView,
    CycleDetailView,
    CycleDemandeRetraitView,
    CycleDepotView,
    CycleSoftDeleteView,
    CycleDirectRetraitView,
    CycleListView,
    CycleUpdateView,
    DashboardView,
    DemandeRetraitListView,
    DemandeRetraitApproveView,
    DemandeRetraitExecuteView,
    DemandeRetraitRejectView,
    MyClientSpaceView,
    MonolithLoginView,
    MonolithLogoutView,
    MouvementListView,
    NotificationListView,
    NotificationReadView,
    NotificationReadAllView,
)

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("login/", MonolithLoginView.as_view(), name="login"),
    path("logout/", MonolithLogoutView.as_view(), name="logout"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/<int:pk>/read/", NotificationReadView.as_view(), name="notification-read"),
    path("notifications/read-all/", NotificationReadAllView.as_view(), name="notification-read-all"),
    path("mon-espace/", MyClientSpaceView.as_view(), name="my-client-space"),
    path("clients/", ClientListView.as_view(), name="clients"),
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client-detail"),
    path("clients/<int:pk>/modifier/", ClientUpdateView.as_view(), name="client-update"),
    path("clients/<int:pk>/compte/", ClientAccountToggleView.as_view(), name="client-account-toggle"),
    path("clients/<int:pk>/supprimer/", ClientSoftDeleteView.as_view(), name="client-soft-delete"),
    path("clients/<int:pk>/retraits/", ClientRetraitView.as_view(), name="client-retrait"),
    path("agents/", AgentListView.as_view(), name="agents"),
    path("agents/<int:pk>/", AgentDetailView.as_view(), name="agent-detail"),
    path("agents/<int:pk>/modifier/", AgentUpdateView.as_view(), name="agent-update"),
    path("agents/<int:pk>/compte/", AgentAccountToggleView.as_view(), name="agent-account-toggle"),
    path("agents/<int:pk>/supprimer/", AgentSoftDeleteView.as_view(), name="agent-soft-delete"),
    path("cycles/", CycleListView.as_view(), name="cycles"),
    path("commissions/", CommissionCycleListView.as_view(), name="commissions"),
    path("demandes-retrait/", DemandeRetraitListView.as_view(), name="demandes-retrait"),
    path("cycles/<int:pk>/", CycleDetailView.as_view(), name="cycle-detail"),
    path("cycles/<int:pk>/modifier/", CycleUpdateView.as_view(), name="cycle-update"),
    path("cycles/<int:pk>/depots/", CycleDepotView.as_view(), name="cycle-depot"),
    path("cycles/<int:pk>/retrait-direct/", CycleDirectRetraitView.as_view(), name="cycle-retrait-direct"),
    path("cycles/<int:pk>/supprimer/", CycleSoftDeleteView.as_view(), name="cycle-soft-delete"),
    path("cycles/<int:pk>/demandes-retrait/", CycleDemandeRetraitView.as_view(), name="cycle-demande-retrait"),
    path("demandes-retrait/<int:pk>/valider/", DemandeRetraitApproveView.as_view(), name="demande-retrait-approve"),
    path("demandes-retrait/<int:pk>/rejeter/", DemandeRetraitRejectView.as_view(), name="demande-retrait-reject"),
    path("demandes-retrait/<int:pk>/executer/", DemandeRetraitExecuteView.as_view(), name="demande-retrait-execute"),
    path("mouvements/", MouvementListView.as_view(), name="mouvements"),
    path("admin/", admin.site.urls),
]
